engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
ratings:
  paths:
  - "src/*.mjs"

exclude_paths:
- "test/"
- "dist/"
- "design/"
- "node_modules/"
