language: node_js
node_js:
- '7'
before_install:
- npm install codecov -g
- npm install -g codeclimate-test-reporter
after_success:
- codecov -e TRAVIS_NODE_VERSION -f coverage/coverage.json
- codeclimate < ./coverage/lcov.info
before_deploy:
- npm install uglify-es
- bash min.sh
deploy:
  provider: npm
  skip_cleanup: true
  email: kariminfo0@gmail.com
  api_key:
    secure: YDtfzzOgnj/NVGCHDegAFWIFbmIhJmmDzpJ7NH1hOfzAiAzUxfotAAYYIvEoSmjMQANQ11NGAjPeJB29qDUrMeb5gu6AA4QaDve/L8fCydrLU6bGh6OByuppxyCLetDSRIMxi2oOYpYfZDLZRLIn1ZCDAJ0rEmZii3dsyZ1TAMrrr/3MI4H2JBQbnhtH/bBAAufDkCg8EKIi5mrhHN887pvIZbKmFX7dfz5PSEjN83F69GpqF4/ZWrd3gZ1A1gm2eYhvm927MGwXblp+GRws0DlJs7NdC4ZCU/TxvlM3GrogECN3v2LCHhQb1BTjmtVxcQFgR1XrlrWJeIdkvuPiRs0WJfWnLq7KZFy8HvMn7+A4T0g+OSuw12Pexq0ty9fdlJjxI9dISsAgvtEkT7gZZgc/QQoebjRnhSNdsLi/yEQ4fWfwv4mUJEBTF+EFl3twJs8BCsVnhgieWPKF9NVkk+V8sQY2ujOQLUSnSL1oPLIfiC1PRYzzN50g4UrJKn+c3c8wi7cKHThH34SKgPz2+b/PxxS0TsWxZGLlyFRfHz78niCgTcYBcKHawEj1r8/XJd5kU5bD6nOAZtEIacOUHAiveGv4+MUlAlnG/WvUN/A04Iqswt9NPh1spyd9UCJau0kCgMnDGj4pnVd61gnzsAs4ErkhZO88kfVsE18MKwQ=
